name: Twitter Bot Runner - Every 30 Minutes

on:
  schedule:
    # Run every 30 minutes
    - cron: '0 * * * *'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      force:
        description: 'Force execution (ignore timing conditions)'
        required: false
        type: boolean
        default: false

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create environment file
      run: |
        cat > .env << EOF
        TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }}
        GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
        TWITTER_USERNAME=${{ secrets.TWITTER_USERNAME }}
        TWITTER_PASSWORD=${{ secrets.TWITTER_PASSWORD }}
        TWITTER_EMAIL=${{ secrets.TWITTER_EMAIL }}
        BOT_USERNAME=${{ secrets.BOT_USERNAME }}
        TARGET_ACCOUNTS=${{ secrets.TARGET_ACCOUNTS }}
        TWITTER_COOKIES=${{ secrets.TWITTER_COOKIES }}
        EOF
    
    - name: Install Chrome for engagement
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
    
    - name: Run Twitter Bot
      env:
        DISPLAY: :99
      run: |
        if [ "${{ inputs.force }}" == "true" ]; then
          echo "Running bot with force flag (manual trigger only)..."
          python main.py auto --force
        else
          echo "Running bot in auto mode (respecting internal conditions)..."
          python main.py auto
        fi
    
    - name: Upload logs and artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bot-logs-${{ github.run_number }}
        path: |
          bot.log
          bot_state.json
          *.xlsx
        retention-days: 7
        if-no-files-found: ignore
    
    - name: Cleanup
      if: always()
      run: |
        pkill -f chrome || true
        pkill -f chromedriver || true
        pkill -f Xvfb || true
